[LKP-3] Added test coverage.
lkaminski96/presence-analyzer-lkaminski pull request #2
Opened 2019-11-19 13:02 UTC by lkaminski96

2019-11-19 16:06 UTC, pwodzinski requested changes

2019-11-19 16:06 UTC, pwodzinski commented on src/presence_analyzer/tests.py
> +        Test calculating mean.
Docstring should be more precise, for example: `Test function for calculating mean.`, or `Test mean() function.`

2019-11-19 16:06 UTC, pwodzinski commented on src/presence_analyzer/tests.py
> +            round(utils.mean([0.3, 0.5, 0.2]), 7),
Please test the exact result returned by the function:
```
        self.assertAlmostEqual(
            utils.mean([0.3, 0.5, 0.2]),
            0.3333333333333333
        )
```

2019-11-19 16:06 UTC, pwodzinski commented on src/presence_analyzer/tests.py
> +            round(utils.mean([1, 3, 3]), 7),
Test case similar to the previous one. There is no need to duplicate tests. If you want to check the function behavior for different types of numbers, just use one case such as:
```
        self.assertEqual(
            utils.mean([-0.3, 1, 0, 2.1]),
            0.7
        )
```

2019-11-19 16:06 UTC, pwodzinski commented on src/presence_analyzer/tests.py
> +            round(utils.mean([-0.3, -0.5, -0.2]), 7),
Duplicate test case

2019-11-19 16:06 UTC, pwodzinski commented on src/presence_analyzer/tests.py
> +        self.assertEqual(
Looks similar as previous case. redundant.

2019-11-19 16:06 UTC, pwodzinski commented on src/presence_analyzer/tests.py
> +        self.assertEqual(
Looks similar as previous case. redundant.

2019-11-19 16:06 UTC, pwodzinski commented on src/presence_analyzer/tests.py
> +        Test intervals.
Better `Test interval() function.`

2019-11-19 16:06 UTC, pwodzinski commented on src/presence_analyzer/tests.py
> +        Test calculating seconds.
Not precise docstring.

2019-11-19 16:06 UTC, pwodzinski commented on src/presence_analyzer/tests.py
> +        self.assertEqual(
A few duplicate cases above. Consider the case of calculation at the end of the range as:
`datetime.time(hour=23, minute=59, second=59)` (IMO also cover the different cases)

2019-11-19 16:06 UTC, pwodzinski commented on src/presence_analyzer/tests.py
> +        Test grouping presence.
Docstring is not clear.

2019-11-19 16:06 UTC, pwodzinski commented on src/presence_analyzer/tests.py
> +            data[1:],
You can test the entire list `data` here.

2019-11-19 16:06 UTC, pwodzinski commented on src/presence_analyzer/tests.py
> +        self.assertListEqual(data[0], [u'Weekday', u'Presence (s)'])
You won't need it if you test the entire `date` list at the same time

2019-11-19 16:06 UTC, pwodzinski commented on src/presence_analyzer/.coveragerc
> +source=/home/lukasz/Devel/presence-analyzer-lkaminski/src/presence_analyzer
We don't want private settings in repo. Remove this file and `.coveragerc` to `.gitignore` file

2019-11-19 16:06 UTC, pwodzinski commented on src/presence_analyzer/tests.py
> +
remove blank line

2019-11-19 16:06 UTC, pwodzinski commented on src/presence_analyzer/tests.py
> +        self.assertTrue(mock_log.debug.called)
I run coverage and noticed that the test does not cover these lines from utils.py line 59-61:
```
            if len(row) != 4:
                # ignore header and footer lines
                continue
```
It is very simple to add such a condition, it is enough to test less than 4 elements in the data file, example:
```
...
11,2013-09-13,13:16:56,15:04:02
11,2013/09/13,13:16:56,15:04:02
12,2013/09/14,13:16:56
```
I would like you to consider creating a separate file only with damaged data like: `broken_data.csv`. Then define this file in line 18: 
```
TEST_BROKEN_DATA_CSV = os.path.join(
    os.path.dirname(__file__), '..', '..', 'runtime', 'data', 'broken_data.csv'
)
```
And finally you can overwrite settings only for one test using this decorator:
```
@patch.dict('presence_analyzer.main.app.config', {'DATA_CSV': TEST_BROKEN_DATA_CSV})
```
if you create a separate file for damaged data, restore the original values in the file `test_data.csv`

2019-11-19 16:07 UTC, pwodzinski commented
Please add description to this PR

2019-11-20 08:17 UTC, lkaminski96 commented
Commit based on ticket:
https://presence-analyzer-lkaminski.atlassian.net/browse/LKP-3

2019-11-20 09:38 UTC, pwodzinski requested changes

2019-11-20 09:38 UTC, pwodzinski commented on src/presence_analyzer/tests.py
> +    @patch.dict(
don't need to overwrite this data, use the `TEST_DATA_CSV` from class setup

2019-11-20 09:38 UTC, pwodzinski commented on src/presence_analyzer/tests.py
> +    @patch.dict(
don't need to overwrite this data, use the `TEST_DATA_CSV` from class setup

2019-11-20 09:38 UTC, pwodzinski commented on src/presence_analyzer/tests.py
> +        self.assertNotIn([12], data.keys())
not needed. all possibilities are already tested line above

2019-11-20 09:57 UTC, pwodzinski approved these changes

2019-11-20 10:12 UTC, merged